/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package CollegeMaster;

import static CollegeMaster.CreateCourse.data;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pankaj kumar
 */
public class courseSubject extends javax.swing.JFrame {

    /**
     * Creates new form courseSubject
     */
    public courseSubject()
    {
        initComponents();
        try
        {
          displayCourseSub();
          displaySubject();
        }
        catch(Exception ex)
        {
            
        }
    }
    FeeInformationBO.PayFeeEM _objPayFeeEM=new FeeInformationBO.PayFeeEM();
 FeeInformationBO.PayFee _objPayFee=new FeeInformationBO.PayFee();
 
     Vector<String> vstring = new Vector<String>();
 public void displayCourseSub() throws SQLException
   {
      
    try
      {
        
      CourseSubjectBO.courseSubject _objCourseSubject=new CourseSubjectBO.courseSubject();
      CourseSubjectBO.courseSubjectEM _objCourSubjectEM=new CourseSubjectBO.courseSubjectEM();
       _objCourseSubject.getCourse(_objCourSubjectEM);
       
       while(_objCourSubjectEM.getResultSet().next())
       {
     // vstring.add(_objCourSubjectEM.getResultSet().getString(2));
       // vstring.add(_objCourSubjectEM.getResultSet().getString(1));
      // vstring.add(_objCourSubjectEM.getResultSet().getInt(1),_objCourSubjectEM.getResultSet().getString(1));
       cmbCourse.addItem(_objCourSubjectEM.getResultSet().getString(2));
         
       }
      //cmbCourse.addItem(vstring);
       
      
     _objCourSubjectEM.getcon().close();
      }
      
      catch(Exception ex)
      {
         ex.printStackTrace();
      }   
   }
  CourseSubjectBO.courseSubject _objCourseSubject=new CourseSubjectBO.courseSubject();
      CourseSubjectBO.courseSubjectEM _objCourSubjectEM=new CourseSubjectBO.courseSubjectEM();
     
 public void displaySubject() throws SQLException
   {
      
    try
      {
        
       _objCourseSubject.getSubject(_objCourSubjectEM);
        Vector<String> vstring = new Vector<String>();
       while(_objCourSubjectEM.getResultSet().next())
       {
     // vstring.add(_objCourSubjectEM.getResultSet().getString(2));
       // vstring.add(_objCourSubjectEM.getResultSet().getString(1));
        // vstring.add(_objCourSubjectEM.getResultSet().getString(2));
        cmbSubject.addItem(_objCourSubjectEM.getResultSet().getString(2));
        
         
       }
      // cmbCourse.addItem(vstring);
     
      
     _objCourSubjectEM.getcon().close();
      }
      
      catch(Exception ex)
      {
         ex.printStackTrace();
      }   
   }
 int courseId=0;
  public void getCourseSubID() throws SQLException
   {
      
    try
      {
        
          _objPayFeeEM.setcourseName(cmbCourse.getSelectedItem().toString());
       _objPayFee.getCourseID(_objPayFeeEM);
 
       while(_objPayFeeEM.getResultSet().next())
       {
     courseId=Integer.parseInt(_objPayFeeEM.getResultSet().getString(1));
       }
      //cmbCourse.addItem(vstring);
       
      
     _objPayFeeEM.getcon().close();
      }
      
      catch(Exception ex)
      {
         ex.printStackTrace();
      }   
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCourse = new javax.swing.JComboBox();
        cmbSubject = new javax.swing.JComboBox();
        cmbForYear = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmbCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbCourseMouseClicked(evt);
            }
        });
        cmbCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCourseActionPerformed(evt);
            }
        });

        cmbSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbSubjectMouseClicked(evt);
            }
        });
        cmbSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSubjectActionPerformed(evt);
            }
        });

        cmbForYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I", "II", "III", "IV" }));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");

        jLabel1.setText("Course");

        jLabel2.setText("Subject");

        jLabel3.setText("Year");

        jLabel4.setText("Description");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        jButton3.setText("Close");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbSubject, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbForYear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbForYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCourseActionPerformed
     txtDescription.setText(cmbCourse.getSelectedItem().toString());
      try
        {
        getCourseSubID();
        }
        catch(Exception ex)
        {
            
        }
     
    }//GEN-LAST:event_cmbCourseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        if(courseId==0 && SubjectId==0)
        {
            
        }
        else
        {
        _objCourSubjectEM.setcoiuseSubjectId(0);
     _objCourSubjectEM.setcourseId(courseId);
     _objCourSubjectEM.setsubjectId(SubjectId);
     _objCourSubjectEM.setforYear(cmbForYear.getSelectedItem().toString());
     _objCourSubjectEM.setdescripton(txtDescription.getText());
     _objCourseSubject.addCourseSubject(_objCourSubjectEM);
      JOptionPane.showMessageDialog(rootPane, "Course Subject Added Success Fully");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbCourseMouseClicked
        
    }//GEN-LAST:event_cmbCourseMouseClicked

    private void cmbSubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbSubjectMouseClicked
        
    }//GEN-LAST:event_cmbSubjectMouseClicked

    private void cmbSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSubjectActionPerformed
         try
        {
         getSubjectID();
        }
        catch(Exception ex)
        {
           
        }
    }//GEN-LAST:event_cmbSubjectActionPerformed
 int SubjectId=0;
 SubjectBO.AddSubjectEM objAddSubjectEM=new SubjectBO.AddSubjectEM();
 SubjectBO.AddSubject objAddSubject=new SubjectBO.AddSubject();
  public void getSubjectID() throws SQLException
   {
      
    try
      {
        
          objAddSubjectEM.setSubjectName(cmbSubject.getSelectedItem().toString());
       objAddSubject.getSubjectId(objAddSubjectEM);
 
       while(objAddSubjectEM.getResultSet().next())
       {
     SubjectId=Integer.parseInt(objAddSubjectEM.getResultSet().getString(1));
       }
      //cmbCourse.addItem(vstring);
       
      
     objAddSubjectEM.getcon().close();
      }
      
      catch(Exception ex)
      {
         ex.printStackTrace();
      }   
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(courseSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(courseSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(courseSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(courseSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new courseSubject().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbCourse;
    private javax.swing.JComboBox cmbForYear;
    private javax.swing.JComboBox cmbSubject;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables
}
