/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeData;

import static EmployeeData.EmployeeQualification.data;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pankaj kumar
 */
public class EmployeeList extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeList
     */
    public EmployeeList() {
        initComponents();
         try
        {
        displayEmployee();
        }
        catch(Exception ex)
        {
            
        }
    }
     EmployeeBO.IEmployeeEM _objeEmployeeEM =new EmployeeBO.IEmployeeEM();
    EmployeeBO.Employee _OBJEmployee=new EmployeeBO.Employee();
static Vector<Vector<String>> data = new Vector<Vector<String>>();

    public void displayEmployee() throws SQLException
     {
      data.clear();
    try
      {
      _OBJEmployee.getEmployeeList(_objeEmployeeEM);
        Vector<String> columnNames = new Vector<String>();
        columnNames.add("EmployeeId");
        columnNames.add("EmployeeName");
        columnNames.add("Designation");
        columnNames.add("Specialization");
        columnNames.add("JoiningDate");
        columnNames.add("Country");
        columnNames.add("State");
        columnNames.add("City");
        columnNames.add("Town");
        columnNames.add("Colony");
        columnNames.add("Pincode");
        columnNames.add("Contact1");
        columnNames.add("Contact2");
        columnNames.add("EmailId");
        
       while(_objeEmployeeEM.getResultSet().next())
       {
             Vector<String> vstring = new Vector<String>();
             vstring.add(_objeEmployeeEM.getResultSet().getString(1));
             vstring.add(_objeEmployeeEM.getResultSet().getString(2));
             vstring.add(_objeEmployeeEM.getResultSet().getString(3));
             vstring.add(_objeEmployeeEM.getResultSet().getString(4));
             vstring.add(_objeEmployeeEM.getResultSet().getString(5));
             vstring.add(_objeEmployeeEM.getResultSet().getString(6));
             vstring.add(_objeEmployeeEM.getResultSet().getString(7));
             vstring.add(_objeEmployeeEM.getResultSet().getString(8));
             vstring.add(_objeEmployeeEM.getResultSet().getString(9));
             vstring.add(_objeEmployeeEM.getResultSet().getString(10));
             vstring.add(_objeEmployeeEM.getResultSet().getString(11));
             vstring.add(_objeEmployeeEM.getResultSet().getString(12));
             vstring.add(_objeEmployeeEM.getResultSet().getString(13));
             vstring.add(_objeEmployeeEM.getResultSet().getString(14));
             
        
       data.add(vstring);
         
       }
      DefaultTableModel model = new DefaultTableModel(data, columnNames);
        tbladmissiondata2.setModel(model);
     
      
     _objeEmployeeEM.getcon().close();
      }
      
      catch(Exception ex)
      {
         ex.printStackTrace();
      }   
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbladmissiondata2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbladmissiondata2.setBackground(new java.awt.Color(204, 204, 255));
        tbladmissiondata2.setForeground(new java.awt.Color(204, 51, 0));
        tbladmissiondata2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null,null, null, null, null,null, null, null, null,null,null},
                {null, null, null, null,null, null, null, null,null, null, null, null,null,null},
                {null, null, null, null,null, null, null, null,null, null, null, null,null,null},
                {null, null, null, null,null, null, null, null,null, null, null, null,null,null}
            },
            new String [] {
                "EmployeeId", "EmployeeName", "Designation", "Specialization","JoiningDate", "Country", "State", "City","Town", "Colony", "Pincode", "Contact1","Contact2", "EmailId"
            }
        ));
        jScrollPane1.setViewportView(tbladmissiondata2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 957, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeList().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbladmissiondata2;
    // End of variables declaration//GEN-END:variables
}
