/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentData;

import static StudentData.StudentPreviousDetail.data;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pankaj kumar
 */
public class StudentList extends javax.swing.JFrame {

    /**
     * Creates new form StudentList
     */
    public StudentList() {
        initComponents();
         try
        {
        displayStudent();
        }
        catch(Exception ex)
        {
            
        }
    }
  StudentPrviousDetailBO.PreviousDetail _objPreviousDetail=new StudentPrviousDetailBO.PreviousDetail();
      StudentPrviousDetailBO.PreviousDetailEM _objPreviousDetailEM=new StudentPrviousDetailBO.PreviousDetailEM();
    int r=0;
   static Vector<Vector<String>> data = new Vector<Vector<String>>();

    public void displayStudent() throws SQLException
     {
      data.clear();
    try
      {
      _objPreviousDetail.getStudentList(_objPreviousDetailEM);
        Vector<String> columnNames = new Vector<String>();
        columnNames.add("AdmissionId");
        columnNames.add("StudentName");
        columnNames.add("DateOfAdmission");
        columnNames.add("Gender");
        columnNames.add("DateOfBirth");
        columnNames.add("Colony");
        columnNames.add("City");
        columnNames.add("Pincode");
        columnNames.add("State");
        columnNames.add("Country");
        columnNames.add("Contact1");
        columnNames.add("Contact2");
        columnNames.add("EmailId");
       while(_objPreviousDetailEM.getResultSet().next())
       {
             Vector<String> vstring = new Vector<String>();
             vstring.add(_objPreviousDetailEM.getResultSet().getString(1));
             vstring.add(_objPreviousDetailEM.getResultSet().getString(2));
             vstring.add(_objPreviousDetailEM.getResultSet().getString(3));
             vstring.add(_objPreviousDetailEM.getResultSet().getString(4));
             vstring.add(_objPreviousDetailEM.getResultSet().getString(5));
             vstring.add(_objPreviousDetailEM.getResultSet().getString(6));
             vstring.add(_objPreviousDetailEM.getResultSet().getString(7));
             vstring.add(_objPreviousDetailEM.getResultSet().getString(8));
             vstring.add(_objPreviousDetailEM.getResultSet().getString(9));
             vstring.add(_objPreviousDetailEM.getResultSet().getString(10));
             vstring.add(_objPreviousDetailEM.getResultSet().getString(11));
             vstring.add(_objPreviousDetailEM.getResultSet().getString(12));
              vstring.add(_objPreviousDetailEM.getResultSet().getString(13));
        
       data.add(vstring);
         
       }
      DefaultTableModel model = new DefaultTableModel(data, columnNames);
        tbladmissiondata2.setModel(model);
     
      
     _objPreviousDetailEM.getcon().close();
      }
      
      catch(Exception ex)
      {
         ex.printStackTrace();
      }   
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbladmissiondata2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbladmissiondata2.setBackground(new java.awt.Color(204, 204, 255));
        tbladmissiondata2.setForeground(new java.awt.Color(204, 0, 0));
        tbladmissiondata2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null,null, null, null,null, null, null,null, null, null},
                {null, null, null, null,null, null, null,null, null, null,null, null, null},
                {null, null, null, null,null, null, null,null, null, null,null, null, null},
                {null, null, null, null,null, null, null,null, null, null,null, null, null}
            },
            new String [] {
                "AdmissionId", "StudentName", "DateOfAdmission", "Gender","DateOfBirth", "Colony", "City", "Pincode","State", "Country", "Contact1", "Contact2","EmailiD"
            }
        ));
        jScrollPane1.setViewportView(tbladmissiondata2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentList().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbladmissiondata2;
    // End of variables declaration//GEN-END:variables
}
